# conda deactivate; conda env remove -y -n mkmf_test; conda create -n mkmf_test -c ians_local mkmf; conda activate mkmf_test;

package:
  name: mkmf
  version: 'alpha'
#  version: '{{ environ.get("GIT_DESCRIBE_TAG", data.get("version")) }}'

source:
  path: .

build:
  script:
    - cp mkmf/bin/mkmf $PREFIX/bin
    - cp mkmf/bin/list_paths $PREFIX/bin
    - cp mkmf/bin/git-version-string $PREFIX/bin


requirements:
  host:
    - conda-forge::perl
    - conda-forge::tcsh
    - conda-forge::bats-core
  run:
    - conda-forge::perl
    - conda-forge::tcsh
    - conda-forge::bats-core

test:
  requires:
    - conda-forge::perl
    - conda-forge::tcsh
    - conda-forge::bats-core
  source_files:
      - t/
  commands:
    - which mkmf
    - mkmf
    - bats --verbose-run t/t000-basic.sh
    - bats --verbose-run t/t001-list_paths.sh || echo "failure guard :-("
    - bats --verbose-run t/t002-git-version-string.sh || echo "failure guard :-("
    - bats --verbose-run t/t003-mkmf.sh
    - bats --verbose-run t/t004-templates.sh


  
about:
  home: https://github.com/NOAA-GFDL/mkmf




        
