name: publish_conda
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fre-cli:miniconda24.7.1_gcc14.2.0
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run Conda to Build
        run: |
          # append the reqd channels
          conda config --append channels conda-forge
          conda config --append channels noaa-gfdl

          # install conda-build and conda-verify
          conda install conda-build conda-verify

          # set token and upload preference
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          conda config --set anaconda_upload yes

          # conda build
          conda build .
